In [2]:
import numpy as np


Loading the data:

In [3]:
data = np.loadtxt('data.csv', delimiter=',')

data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

*spliting the data:*

In [4]:
input_data = data[: , 0:8]
output_data = data[: , 8]

In [5]:
input_data

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]],
      shape=(768, 8))

In [6]:
output_data

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [7]:
ones =0
zeros=0
for i in output_data:
    if i==1:
        ones+=1
    else:
        zeros+=1
        
print("Number of ones: ", ones)
print("Number of zeros: ", zeros)

Number of ones:  268
Number of zeros:  500


#### Building Machine Learning Model:

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

I0000 00:00:1787032948.533427   14503 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1787032948.534889   14503 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1787032948.795438   14503 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1787032950.673559   14503 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:0

In [9]:
# Note: This is the old way of creating a TensorFlow model.
# The newest way is to use the functional API.
# But for this project, we will use the old way.

model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid')) #Sigmoid function is used for binary classification problems

/home/muh7/.pyenv/versions/ai_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1787032954.134880   14503 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1787032954.153423   14503 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [39]:
# here is the new way of creating a model using:
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Input(shape=(8,)),
    Dense(24, activation="relu"),
    Dense(12, activation="relu"),
    Dense(8, activation="relu"),
    Dense(1, activation="sigmoid")
])

#### Set the Configuration:

In [40]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#### Train The ML Model:

In [41]:
model.fit(input_data, output_data, epochs=250, batch_size=20, verbose=1)

Epoch 1/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4674 - loss: 3.6803    
Epoch 2/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5768 - loss: 1.3610 
Epoch 3/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6016 - loss: 0.8380 
Epoch 4/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5990 - loss: 0.7706 
Epoch 5/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6185 - loss: 0.7347 
Epoch 6/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6432 - loss: 0.7053 
Epoch 7/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6680 - loss: 0.6686 
Epoch 8/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6536 - loss: 0.6474 
Epoch 9/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6201 
Epoch 10/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6888 - loss: 0.6000 
Epoch 11/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6914 - loss: 0.6013 
Epoch 12/250
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/st

#### Evaluate The Accuracy:

In [42]:
accuracy = model.evaluate(input_data, output_data)

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8177 - loss: 0.4024 


In [43]:
accuracy = model.evaluate(input_data, output_data, verbose=0)
accuracy

[0.4023653566837311, 0.8177083134651184]

In [44]:
print("Accuracy: %.2f %%" % (accuracy[1]*100))

Accuracy: 81.77 %


#### Make Prediction:

In [45]:
predictions = model.predict(input_data)
predictions = (predictions>0.5).astype(int) # astype is used to convert the boolean values to integer values (0 or 1)
predictions

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

#### Compare The Predicted Data with the Actual Data:

In [46]:
def display(num):
    if num==1:
        return "Diabetic"
    else:
        return "Non-Diabetic"

for i in range(200):
    print(" %s => %s (expected %s)" % (input_data[i].tolist(), display(predictions[i]), display(output_data[i])))

 [6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => Diabetic (expected Diabetic)
 [1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => Non-Diabetic (expected Non-Diabetic)
 [8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => Diabetic (expected Diabetic)
 [1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => Non-Diabetic (expected Non-Diabetic)
 [0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => Diabetic (expected Diabetic)
 [5.0, 116.0, 74.0, 0.0, 0.0, 25.6, 0.201, 30.0] => Non-Diabetic (expected Non-Diabetic)
 [3.0, 78.0, 50.0, 32.0, 88.0, 31.0, 0.248, 26.0] => Non-Diabetic (expected Diabetic)
 [10.0, 115.0, 0.0, 0.0, 0.0, 35.3, 0.134, 29.0] => Non-Diabetic (expected Non-Diabetic)
 [2.0, 197.0, 70.0, 45.0, 543.0, 30.5, 0.158, 53.0] => Diabetic (expected Diabetic)
 [8.0, 125.0, 96.0, 0.0, 0.0, 0.0, 0.232, 54.0] => Diabetic (expected Diabetic)
 [4.0, 110.0, 92.0, 0.0, 0.0, 37.6, 0.191, 30.0] => Non-Diabetic (expected Non-Diabetic)
 [10.0, 168.0, 74.0, 0.0, 0.0, 38.0, 0.537, 34.0] => Diab