In [56]:
import numpy as np


Loading the data:

In [57]:
data = np.loadtxt('data.csv', delimiter=',')

data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

*spliting the data:*

In [58]:
input_data = data[: , 0:8]
output_data = data[: , 8]

In [59]:
input_data

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]],
      shape=(768, 8))

In [60]:
output_data

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [79]:
ones =0
zeros=0
for i in output_data:
    if i==1:
        ones+=1
    else:
        zeros+=1
        
print("Number of ones: ", ones)
print("Number of zeros: ", zeros)

Number of ones:  268
Number of zeros:  500


#### Building Machine Learning Mode:

In [61]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#Note this the old way of creating a model. The new way is to use the functional API. But for this project, we will use the old way.
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid')) #Sigmoid function is used for binary classification problems

/home/muh7/.pyenv/versions/ai_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [108]:
# here is the new way of creating a model using:
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Input(shape=(8,)),
    Dense(12, activation="relu"),
    Dense(8, activation="relu"),
    Dense(1, activation="sigmoid")
])

#### Set the Configuration:

In [109]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#### Train The ML Model:

In [118]:
model.fit(input_data, output_data, epochs=150, batch_size=10)

Epoch 1/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7956 - loss: 0.4284
Epoch 2/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7982 - loss: 0.4266
Epoch 3/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7891 - loss: 0.4344
Epoch 4/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8034 - loss: 0.4276  
Epoch 5/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7904 - loss: 0.4376  
Epoch 6/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8008 - loss: 0.4272
Epoch 7/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7943 - loss: 0.4274  
Epoch 8/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7891 - loss: 0.4357
Epoch 9/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7956 - loss: 0.4261  
Epoch 10/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7956 - loss: 0.4280  
Epoch 11/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7995 - loss: 0.4315
Epoch 12/150
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/

#### Evaluate The Accuracy:

In [119]:
accuracy = model.evaluate(input_data, output_data)

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7969 - loss: 0.4158 


In [120]:
accuracy = model.evaluate(input_data, output_data, verbose=0)
accuracy

[0.4157886505126953, 0.796875]

In [121]:
print("Accuracy: %.2f %%" % (accuracy[1]*100))

Accuracy: 79.69 %


#### Make Prediction:

In [122]:
predictions = model.predict(input_data)
predictions = (predictions>0.5).astype(int) # astype is used to convert the boolean values to integer values (0 or 1)
predictions

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step


array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

#### Compare The Predicted Data with the Actual Data:

In [123]:
def display(num):
    if num==1:
        return "Diabetic"
    else:
        return "Non-Diabetic"

for i in range(200):
    print(" %s => %s (expected %s)" % (input_data[i].tolist(), display(predictions[i]), display(output_data[i])))

 [6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => Diabetic (expected Diabetic)
 [1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => Non-Diabetic (expected Non-Diabetic)
 [8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => Diabetic (expected Diabetic)
 [1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => Non-Diabetic (expected Non-Diabetic)
 [0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => Diabetic (expected Diabetic)
 [5.0, 116.0, 74.0, 0.0, 0.0, 25.6, 0.201, 30.0] => Non-Diabetic (expected Non-Diabetic)
 [3.0, 78.0, 50.0, 32.0, 88.0, 31.0, 0.248, 26.0] => Non-Diabetic (expected Diabetic)
 [10.0, 115.0, 0.0, 0.0, 0.0, 35.3, 0.134, 29.0] => Diabetic (expected Non-Diabetic)
 [2.0, 197.0, 70.0, 45.0, 543.0, 30.5, 0.158, 53.0] => Diabetic (expected Diabetic)
 [8.0, 125.0, 96.0, 0.0, 0.0, 0.0, 0.232, 54.0] => Non-Diabetic (expected Diabetic)
 [4.0, 110.0, 92.0, 0.0, 0.0, 37.6, 0.191, 30.0] => Non-Diabetic (expected Non-Diabetic)
 [10.0, 168.0, 74.0, 0.0, 0.0, 38.0, 0.537, 34.0] => Diab